### ISSUE TITLE
GMRES

### ISSUE THREAD

**Issue by Konstantin8105** [james-bowman/sparse#10]
Could you clarify your point of view about adding implementation for iterative methods?
For example GMRES:
https://en.wikipedia.org/wiki/Generalized_minimal_residual_method

**Comment by Konstantin8105** [comment]
Other methods:
https://www-users.cs.umn.edu/~saad/books.html
http://www.netlib.org/templates/templates.pdf

**Comment by james-bowman** [comment]
To be honest, I would love to add some solvers but have not got around to it yet.  The package so far provides the sparse matrix types themselves, conversion routines between the sparse types and to/from Gonum's mat.Dense and mat.VecDense types and basic arithmetic operations (multiplication, addition, subtraction, etc.).  I would be very interested in discussing any thoughts you have on how best to proceed.

**Comment by Konstantin8105** [comment]
I work on my project for steel structural engineer - FEM. 
https://github.com/Konstantin8105/hd
In my practice, used next:

* solving `A*x=b` for calculate global displacement, where 
A is symmetrical sparse matrix
x is dense vector
b is sparse vector(or matrix)

Now, I use LU decomposition from `gonum`.
So, I will prepare some code just for continue our discussion.

**Comment by james-bowman** [comment]
Ah, Hi Vladimir, I was going to point in your direction, as I knew from the gonum groups you had been looking at this but didn't realise you had that far.  Brilliant work.  Obviously if it works with gonum mat.Matrix and mat.Vector interfaces then it will support the use of sparse matrices/vectors from this package too.  Only drawback I can see is that it probably won't specifically take advantage of the sparsity.

**Comment by vladimir-ch** [comment]
Yea, the work on it definitely does not advance as fast as I'd like.

In `linsolve` the matrix is currently represented by
```
type MulVecToer interface {
	// MulVecTo computes A*x or A^T*x and stores the result into dst.
	MulVecTo(dst []float64, trans bool, x []float64)
}
```
At the moment no type in `mat` or your `sparse` satisfies `MulVecToer` but the interface is not set in stone. It would be actually quite nice if the matrix types directly satisfied an interface that linsolve would take. And it would be even nicer if `sparse` eventually became part of Gonum ... :-) But that's taking this issue far off topic.

**Comment by Konstantin8105** [comment]
Dear Vladimir-ch , I see a great work is done here https://github.com/gonum/exp/pull/1 , but not promoted. Could you clarify information about that PR.

**Comment by vladimir-ch** [comment]
That PR was done initially to outline the final state that I'd like to reach. The actual committed code is coming in smaller PRs and evolved to slightly differ from that outline. https://github.com/gonum/exp/pull/1 will eventually be closed.

**Comment by james-bowman** [comment]
That interface is not bad - should be straightforward to incorporate into the CSR and CSC matrices in the `sparse` package.  It basically looks like a level 2 sparse BLAS operation but with the receiver representing operand A rather than the result as with most Gonum methods which will allow a degree of polymorphism.

> ...And it would be even nicer if sparse eventually became part of Gonum ... :-) But that's taking this issue far off topic.

Yes, indeed.  That is an ongoing discussion - I would love to and that definitely is my intention but suspect it will take some time.

**Comment by james-bowman** [comment]
I have added `MulVecTo(dst []float64, trans bool, x []float64)` methods to both CSR and CSC matrix types which should make them directly compatible with `linsolve` (https://github.com/gonum/exp/tree/master/linsolve).  I will add the methods to the other sparse matrix types (DOK, COO and potentially DIA) at some point when I get a chance although internally these methods will probably just convert the receiver to a CSR matrix and call `MulVecTo(dst []float64, trans bool, x []float64)` on it.

**Comment by james-bowman** [comment]
`MulVecTo(dst []float64, trans bool, x []float64)` methods are now implemented on all sparse matrix types: CSR, CSC, COO, DOK and DIA.
