### ISSUE TITLE
Sparse vectors in blas package

### ISSUE THREAD

**Issue by JZabihi** [james-bowman/sparse#11]
Hi. I'm just wondering if you have any plan for adding the sparse vector representation into blas package the same way as the sparse matrix (referring to RawMatrix() method)?. having access to the actual elements of a sparse vector (data and ind) would  be quite useful.
Thanks

**Comment by james-bowman** [comment]
I have added a RawVector() method to the Vector type that allows access to the underlying data and indices of the sparse vector as used by the BLAS routines.
